version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: chronus-postgres
    # Below details will be moved to .env file later. This is kept here for the ease of testing.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chronus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chronus_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: chronus-api
    ports:
      - "3010:3010"
    # Below details will be moved to .env file later. This is kept here for the ease of testing.
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@postgres:5432/chronus_db
      PORT: 3010
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - VITE_API_URL=http://localhost:3010
    container_name: chronus-web
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
